server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # 1. Servir la página web (Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. EL TRUCO MAESTRO: Proxy para el Backend
    # Engañamos al navegador: Si pide "/clinica", Nginx lo redirige internamente al contenedor Java.
    # Al ser una petición interna entre contenedores, NO hay bloqueo CORS.
    location /clinica/ {
        proxy_pass http://clinica-backend:8081/clinica/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}